name: VyOS v1.4 LTS Release
permissions:
  contents: write
on:
  push:
    tags:
      - 'v1.4.0-LTS*'

env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  BRANCH: sagitta
  ARCHITECTURE: amd64
  BUILD_BY: vyos-build-action@github.com
  BUILD_TYPE: release
  VERSION: 1.4.0
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:sagitta
      options: --workdir /vyos --privileged

    steps:
      - name: Clone source code
        run: git clone -b $BRANCH --single-branch $GIT_CLONE_URL

      - name: Build ISO
        working-directory: ./vyos-build
        run: |
          sudo make clean
          sudo ./build-vyos-image iso --architecture $ARCHITECTURE --build-by $BUILD_BY --build-type $BUILD_TYPE --version $VERSION

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vyos-${{ env.VERSION }}-${{ env.ARCHITECTURE }}-iso
          path: vyos-build/build/vyos-${{ env.VERSION }}-*.iso

  release:
      permissions: write-all
      needs: build
      runs-on: ubuntu-latest

      steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: vyos-${{ env.VERSION }}-${{ env.ARCHITECTURE }}-iso

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: VyOS v${{ env.BUILD_VERSION }} LTS Release
          body: VyOS v${{ env.BUILD_VERSION }} LTS Release
          draft: false
          prerelease: false
          files: |
            vyos-${{ env.VERSION }}-${{ env.ARCHITECTURE }}.iso
           
